name: minio
description: Unofficial MinIO Dart Client for Amazon S3 Compatible Cloud Storage.
version: 0.1.0
# homepage: https://www.example.com
author: xuty <root@xuty.tk>

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  meta: ^1.1.7
  http: ^0.12.0+4
  crypto: ^2.1.4
  convert: ^2.1.1
  xml: ^3.7.0
  buffer: ^1.0.6
  intl: ^0.16.1
#  path: ^1.6.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
  html: ^0.14.0+3
